# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# Header
language: r
#matrix: 3x Linux, 1x OS X
matrix:
  include:
  - r: 3.1
  - r: 3.2
  - r: 3.3
  - r: 3.4
  - r: release
    env:
    - BUILD_PKGDOWN: true
  - r: devel

  - os: osx
    osx_image: xcode7.3
    r: release
    latex: false

sudo: false
dist: trusty
latex: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

#services
services:
